### ISSUE TITLE
Why was a class chosen for legtools?

### ISSUE THREAD

**Issue by erikhuizinga** [StackOverflowMATLABchat/legtools#14]
Instead of a `legtools` class, you could have chosen to write multiple functions. What are considerations to go with a class instead of functions? OOP is usually not used to just group functions.

Is it because the end user then has a single interface, being `legtools.`_`method`_, which is more explicit than individual functions (e.g. called `ltappend`, `ltremove`)? A disadvantage is that some MATLAB users, since it is accessible for non-programmers, may not understand how `legtools.method` works.

Or are/were there plans to use the constructor for some general functions, e.g. perform `verchk` for every method being called? In the current state the constructor is void.

**Comment by sco1** [comment]
> Instead of a legtools class, you could have chosen to write multiple functions. What are considerations to go with a class instead of functions? OOP is usually not used to just group functions.

Nothing about OOP precludes it being used simply to group functions. Most OOP languages have static and abstract classes, which do not instantiate an object. This is also the closest thing MATLAB currently has to packages. Yes, it has the [folder hierarchy thing](https://www.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html) but that's unnecessarily convoluted.

> Is it because the end user then has a single interface, being legtools.method, which is more explicit than individual functions (e.g. called ltappend, ltremove)?

Yes. Individual functions are less than ideal here because it would require `*.m` files for every method along with any common helpers. For something as simple as [`legtools` v2.2](https://github.com/StackOverflowMATLABchat/legtools/releases/tag/v2.2) this would require 7 `*.m` files, which is undesirably messy.

>  A disadvantage is that some MATLAB users, since it is accessible for non-programmers, may not understand how legtools.method works.

I don't think you're giving folks enough credit. "How to use `legtools`" is clearly documented.

> Or are/were there plans to use the constructor for some general functions, e.g. perform verchk for every method being called? In the current state the constructor is void.

Static methods by definition do not require an instance of the class and the constructor is not called when they are invoked.
